version: '3.1'

services:
  app:
    build: ./
    environment:
      POSTGRES_DB: hackme
      POSTGRES_USER: hackme
      POSTGRES_PASSWORD: hackme
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - 8080:8080

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: hackme
      POSTGRES_DB: hackme
      POSTGRES_PASSWORD: hackme
    ports:
      - 5432:5432
